language: go
go:
  - 1.9.x

branches:
  only:
    - master

services:
  - docker

before_install:
  - docker --version

script:
  - make prepare
  - mv $GOPATH/src/github.com/docker/docker/vendor/github.com/docker/go-connections/nat $GOPATH/src/github.com/docker/docker/vendor/github.com/docker/go-connections/nonat
  - make
  - sudo ./cn version
  - sudo make tests

after_script:
  - ./cn stop
  - ./cn purge --yes-i-am-sure
