title = "Default flavors"
[default]
  # This section is here to override the default builtins of ceph-nano
  # memory_size = "512MB"
  # use_default = true
  # cpu_count = 1

[medium]
  memory_size="768MB"

[large]
  memory_size="1GB"

[huge]
  cpu_count=2
  memory_size="4GB"
