title = "Ceph Nano test configuration file"

# As per the code, the configuration file is structured like
#[group]
#  [item]
#    itemValue=value

[flavors]
  [flavors.default]
    [flavors.default.ceph.conf]
        osd_memory_target = 536870912
        osd_memory_base = 268435456
        osd_memory_cache_min = 33554432
        bluestore_cache_autotune_chunk_size = 8388608
        osd_min_pg_log_entries = 10
        osd_max_pg_log_entries = 10
        osd_pg_log_dups_tracked = 10
        osd_pg_log_trim_min = 10

  [flavors.test_nano_no_default]
    memory_size="1GB"
    cpu_count=2
    use_default=false
    privileged=true
    data="/dev/sdb1"
    size="20GB"
    work_directory="/tmp/nano/"
    [flavors.test_nano_no_default.ceph.conf]
      osd_memory_target = 3841234556

  [flavors.test_nano_default]
    [flavors.test_nano_default.ceph.conf]
      osd_memory_target = 3841234556

[images]
  [images.default]
    # This section is here to override the default builtins of ceph-nano
    # image_name="registry/username/image:tag"

  [images.real1]
    image_name="ceph/daemon:latest-real1"

  [images.complex]
    image_name="this.url.is.complex/cool/for-a-test"
